### PR TITLE
Changing Socks Shop to Sock Shop

### PR DESCRIPTION
**Pull request by rberlind**
I'm changing Socks Shop to Sock Shop in apcera.md to conform to today's decision to standardize usage of "Sock Shop".  I am also updating files in microservices-demo repository under deploy/apcera to conform in separate pull request in that repository.

### CODE REVIEW

**Comment by rberlind** [comment]
Please note that the conflicts should all be resolved to use singular "sock" instead of "socks"

**Comment by jasonrichardsmith** [comment]
@rberlind this PR has conflicts

**Comment by rberlind** [comment]
Hi @jasonrichardsmith.  I saw that, but don't understand why they occurred.  I'm the only one to have edited the Apcera.md file and the conflicts should be resolved to use singular "sock" instead of "socks".  Is that something you can manually do?  Or can you suggest the procedure for me to fix it?

Thanks,
Roger

**Comment by rberlind** [comment]
will close and re-open to see if the conflicts are resolved.

**Comment by rberlind** [comment]
OK.  I was able to fix it.  Please go ahead and merge when you have time.
Thanks.

**Pull request merged**
